"""Step 3: Mesh generation, cartilage thickness, and region assignment.

Takes a canonical-label segmentation and generates 3D surface meshes for
each bone, computes cartilage thickness per region, and saves meshes as VTK.

Extracts from seg_thick_t2_pipeline.py lines 346-428.

The femur subregion labels (11-15) are *loaded* from the file the `subregions`
step writes, not computed here (D7b). They are used for regional thickness and
nothing else, so they are loaded lazily -- a bones-only model with thickness
off needs no subregions at all -- and their absence costs the femur's five
subregion columns, not the meshes.
"""

import json
import logging
import os
import sys
from pathlib import Path

import numpy as np
import SimpleITK as sitk

from steps._common import (
    emit_progress,
    find_segmentation,
    image_prefix,
    load_segmentation,
    load_subregions,
    parse_step_args,
    write_step_result,
)
from steps.subregions import FEMUR_SUBREGION_LABELS

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

# Bone configuration using CANONICAL label indices.
# The old monolith used DOSMA-native labels (femur=7, fem_cart=2) because it
# ran before any remapping. This step runs AFTER label_remap.
BONE_CONFIG = {
    "femur": {
        "tissue_idx": 1,         # CANONICAL femur_bone
        "list_cart_labels": [4], # CANONICAL femur_cart
        "n_points": 20000,
        "crop_percent": 0.8,
    },
    "tibia": {
        "tissue_idx": 2,            # CANONICAL tibia_bone
        "list_cart_labels": [5, 6], # CANONICAL tibia_cart_med, tibia_cart_lat
        "n_points": 20000,
        "crop_percent": 0.8,
    },
    "patella": {
        "tissue_idx": 3,         # CANONICAL patella_bone
        "list_cart_labels": [7], # CANONICAL patella_cart
        "n_points": 10000,
        "crop_percent": None,    # patella: never crop
    },
}

# FEMUR_SUBREGION_LABELS (11-15) is imported from steps.subregions, which is
# what writes them -- one definition, at the point of creation. Re-exported here
# because this module is where consumers have always looked for it.

# Mapping from subregion label to human-readable region name (canonical).
# Used for naming thickness metrics in the results dict.
CANONICAL_REGION_NAMES = {
    # Cartilage regions (from subregion segmentation)
    4: "fem_cart",
    5: "med_tib_cart",
    6: "lat_tib_cart",
    7: "pat_cart",
    # Femur subregions (generated by pymskt)
    11: "ant_fem_cart",
    12: "med_wb_fem_cart",
    13: "lat_wb_fem_cart",
    14: "med_post_fem_cart",
    15: "lat_post_fem_cart",
}


def run(working_dir, options=None, config=None):
    """Run mesh generation and cartilage thickness step.

    Args:
        working_dir: Directory containing canonical-label segmentation.
        options: Dict with optional keys:
            - compute_thickness: bool (default True)
            - cartilage_smoothing: float (default 0.3125)
        config: Pipeline config dict (unused currently -- bone config is
                hardcoded with canonical labels).

    Returns:
        Dict with metrics, bones_processed, thickness_computed, and
        has_subregions -- False when the subregions step did not run, in which
        case femoral thickness is reported for the whole cartilage rather than
        its five subregions.
    """
    import pymskt as mskt

    working_dir = Path(working_dir)
    options = options or {}
    compute_thickness = options.get("compute_thickness", True)
    cartilage_smoothing = options.get("cartilage_smoothing", 0.3125)

    emit_progress(0, "Loading segmentation")
    sitk_seg = load_segmentation(working_dir)

    # Determine filename prefix from the segmentation file name. The prefix is
    # the same whichever format was read -- output names must not move because
    # the read format did.
    filename_prefix = image_prefix(find_segmentation(working_dir))

    # The femur subregion labels come from the subregions step. They are used
    # only for regional thickness, so they are loaded here rather than at the
    # top: with thickness off -- a bones-only model -- this step needs no
    # subregions at all. Without them, thickness is still computed, over whole
    # cartilage regions instead of the femur's five subregions.
    sitk_seg_subregions = None
    if compute_thickness:
        emit_progress(5, "Loading subregion segmentation")
        try:
            sitk_seg_subregions = load_subregions(working_dir)
        except FileNotFoundError:
            logging.warning(
                "No *_subregions-labels image in %s. Computing whole-region femoral "
                "cartilage thickness instead of the five subregions.",
                working_dir,
            )
    has_subregions = sitk_seg_subregions is not None

    # Per-bone mesh generation
    dict_results = {}
    bone_names = list(BONE_CONFIG.keys())
    for i, (bone_name, bone_config) in enumerate(BONE_CONFIG.items()):
        pct = 15 + int(70 * i / len(bone_names))
        emit_progress(pct, f"Generating {bone_name} mesh")

        bone_mesh = mskt.mesh.BoneMesh(
            seg_image=sitk_seg,
            label_idx=bone_config["tissue_idx"],
            list_cartilage_labels=bone_config["list_cart_labels"],
            bone=bone_name,
            crop_percent=bone_config["crop_percent"],
        )
        bone_mesh.create_mesh(smooth_image_var=0.5)

        # Save raw mesh before pyacvd resampling (needed for NSM fitting)
        if bone_name == "femur":
            raw_mesh = bone_mesh.copy()
            raw_mesh.save_mesh(str(working_dir / "femur_mesh_raw.vtk"))

        bone_mesh.resample_surface(clusters=bone_config["n_points"])
        bone_mesh.fix_mesh()

        if compute_thickness:
            bone_mesh.calc_cartilage_thickness(image_smooth_var_cart=cartilage_smoothing)
            bone_mesh.seg_image = sitk_seg_subregions if has_subregions else sitk_seg

            for cart_mesh in bone_mesh.list_cartilage_meshes:
                cart_mesh.fix_mesh()

            # For femur, use pymskt subregion labels for regional thickness
            if bone_name == "femur" and has_subregions:
                cart_labels = FEMUR_SUBREGION_LABELS
                bone_mesh.list_cartilage_labels = cart_labels
            else:
                cart_labels = bone_config["list_cart_labels"]

            bone_mesh.assign_cartilage_regions()

            # Compute thickness statistics per region
            thickness = np.array(bone_mesh.get_scalar("thickness (mm)"))
            regions = np.array(bone_mesh.get_scalar("labels"))

            for region in cart_labels:
                region_name = CANONICAL_REGION_NAMES.get(region, f"region_{region}")
                region_thickness = thickness[regions == region]
                dict_results[f"{region_name}_mm_mean"] = float(np.nanmean(region_thickness))
                dict_results[f"{region_name}_mm_std"] = float(np.nanstd(region_thickness))
                dict_results[f"{region_name}_mm_median"] = float(np.nanmedian(region_thickness))

        # Save meshes
        bone_mesh.save_mesh(str(working_dir / f"{bone_name}_mesh.vtk"))
        if compute_thickness:
            for cart_idx, cart_mesh in enumerate(bone_mesh.list_cartilage_meshes):
                cart_mesh.save_mesh(str(working_dir / f"{bone_name}_cart_{cart_idx}_mesh.vtk"))

    emit_progress(90, "Saving results")
    # Save thickness metrics
    if dict_results:
        import pandas as pd
        df = pd.DataFrame([dict_results])
        df.to_csv(str(working_dir / f"{filename_prefix}_thickness_results.csv"), index=False)
        with open(str(working_dir / f"{filename_prefix}_thickness_results.json"), "w") as f:
            json.dump(dict_results, f, indent=4)

    emit_progress(100, "Mesh generation complete")
    return {
        "metrics": dict_results,
        "bones_processed": bone_names,
        "thickness_computed": compute_thickness,
        "has_subregions": has_subregions,
    }


if __name__ == "__main__":
    args = parse_step_args()
    result = run(args.working_dir, args.options, args.config)
    write_step_result(args.working_dir, result)
